import platform

if platform.system() == "Windows":
    from .msg import parse_msg  # type: ignore
    from .base import Message, BaseMessage, HumanMessage  # type: ignore
    from .mattr import (  # type: ignore
        SystemMessage,
        TickleMessage,
        TimeMessage,
        FriendMessage,
        SelfMessage,
    )
    from .type import (  # type: ignore
        TextMessage,
        QuoteMessage,
        ImageMessage,
        VoiceMessage,
        VideoMessage,
        FileMessage,
        LocationMessage,
        LinkMessage,
        EmotionMessage,
        MergeMessage,
        PersonalCardMessage,
        OtherMessage,
    )
    from .self import (  # type: ignore
        SelfMessage,
        SelfQuoteMessage,
        SelfTextMessage,
        SelfVoiceMessage,
        SelfImageMessage,
        SelfVideoMessage,
        SelfFileMessage,
        SelfLocationMessage,
        SelfLinkMessage,
        SelfEmotionMessage,
        SelfMergeMessage,
        SelfPersonalCardMessage,
        SelfOtherMessage,
    )
    from .friend import (  # type: ignore
        FriendMessage,
        FriendQuoteMessage,
        FriendTextMessage,
        FriendVoiceMessage,
        FriendImageMessage,
        FriendVideoMessage,
        FriendFileMessage,
        FriendLocationMessage,
        FriendLinkMessage,
        FriendEmotionMessage,
        FriendMergeMessage,
        FriendPersonalCardMessage,
        FriendOtherMessage,
    )

    __all__ = [
        "parse_msg",
        "Message",
        "BaseMessage",
        "HumanMessage",
        "SystemMessage",
        "TickleMessage",
        "TimeMessage",
        "FriendMessage",
        "SelfMessage",
        "TextMessage",
        "QuoteMessage",
        "ImageMessage",
        "VoiceMessage",
        "VideoMessage",
        "FileMessage",
        "LocationMessage",
        "LinkMessage",
        "EmotionMessage",
        "MergeMessage",
        "PersonalCardMessage",
        "OtherMessage",
        "SelfMessage",
        "SelfQuoteMessage",
        "SelfTextMessage",
        "SelfVoiceMessage",
        "SelfImageMessage",
        "SelfVideoMessage",
        "SelfFileMessage",
        "SelfLocationMessage",
        "SelfLinkMessage",
        "SelfEmotionMessage",
        "SelfMergeMessage",
        "SelfPersonalCardMessage",
        "SelfOtherMessage",
        "FriendMessage",
        "FriendQuoteMessage",
        "FriendTextMessage",
        "FriendVoiceMessage",
        "FriendImageMessage",
        "FriendVideoMessage",
        "FriendFileMessage",
        "FriendLocationMessage",
        "FriendLinkMessage",
        "FriendEmotionMessage",
        "FriendMergeMessage",
        "FriendPersonalCardMessage",
        "FriendOtherMessage",
    ]
else:
    __all__ = []